version: '3'

volumes:
  foodgram_pg_data:
  static:
  backend_static:
  media:

services:
  foodgram_db:
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
  backend:
    image: titkovaa/foodgram_backend
    env_file: .env
    depends_on:
      - foodgram_db
    volumes:
      - backend_static:/app/collected_static
      - media:/media
  frontend:
    env_file: .env
    image: titkovaa/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      - ./frontend/:/app/result_build/
  nginx:
    image: titkovaa/foodgram_nginx
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
      - backend_static:/backend_static
      - media:/media
      # - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend